name: Build APK with Official Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK using Official Docker
        run: |
          docker run --rm \
          -e MAKEFLAGS="-j1" \
          -v ${{ github.workspace }}:/home/user/hostcwd \
          kivy/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk